### ISSUE TITLE
Add Fork Link

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#21]
We need to add a link on each page somewhere that asks people to fork the site on github! This doesn't have to be a corner ribbon saying "Fork me!", but I'm not opposed to it. Another place to put it could be in the footer. Any ideas?

**Comment by JohnLZeller** [comment]
What do we think of using the github ribbon? Too distracting?
If not this, then what?

![](http://s30.postimg.org/vpvxpqd6p/Screen_Shot_2014_04_14_at_3_08_04_PM.png)

**Comment by josephspens** [comment]
We can put it in the footer

**Comment by JohnLZeller** [comment]
Okay, how's this?

![](http://s22.postimg.org/791llz39t/Screen_Shot_2014_04_15_at_8_28_11_AM.png)

**Comment by josephspens** [comment]
Nah, just leave it I'll add a link.

This isn't software, the main purpose of the website isn't to get people to work on it. We can add Github to the social media icons and link it back to the project, but it shouldn't be right in your face.

Also this isn't the latest footer.

**Comment by JohnLZeller** [comment]
Ah, shoot, I see the new footer now :P

**Comment by JohnLZeller** [comment]
Github icon added instead of a fork link in revision a46fe8c7682ab155018eaa34fdf4b4aaf38dea54

**Comment by JohnLZeller** [comment]
Find a new home for the github link permanently
