### ISSUE TITLE
Budget Graph isn't showing up in Firefox

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#27]
The budget graph on the front page is not showing up in Firefox.

**Comment by JohnLZeller** [comment]
Also, the social media buttons aren't showing on Firefox either

**Comment by josephspens** [comment]
The graph not showing is a Firefox bug, I can't seem to find anyone with a similar issue. I'm going to work on this one last, but I don't want to push back release so we may just show an image of the graph in firefox.

**Comment by JohnLZeller** [comment]
Sounds good to me, I think that's a good bandaid for the initial release
