### ISSUE TITLE
Sidebar is falling under main container

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#32]
The sidebar is falling under the main container because it appears that the main containers width is too large.
This is happening in both Firefox and Chrome.
Happens on every page except for the front blog roll. Still happens on blog post pages though.

![](http://s29.postimg.org/nam2obn87/Screen_Shot_2014_04_15_at_11_36_14_AM.png)

**Comment by josephspens** [comment]
Ah good catch, in order to do some media query breakpoint magic which made the quick responsive styling turnaround possible, I needed to upgrade our grid framework from v1 to v2. I missed a site wide configuration in the transition.

**Comment by JohnLZeller** [comment]
Ah ha, sweet!

**Comment by JohnLZeller** [comment]
Seems like this is gonna fix some issues with the grid in mobile too, they seem related.

**Comment by JohnLZeller** [comment]
Nice! This fixed some wierdness with the mobile view too
