### ISSUE TITLE
Create FAQ Page

### ISSUE THREAD

**Issue by HackersMuse** [SpaceAdvocates/penny4nasa#38]
http://penny4nasa.cloudcontrolled.com/faq
![screen shot 2014-04-19 at 8 54 16 pm](https://cloud.githubusercontent.com/assets/7350872/2750004/603eb7a2-c840-11e3-9ee3-38a18b32ae34.png)

**Comment by JohnLZeller** [comment]
Wordpress makes some of the pages showing up a little weird. We actually have to create the page in the admin interface and then assign that page to be at /faq

So long story short, I have all the copy for this generated and inserted into the database already. You can see it here: http://www.penny4nasa.org/faq/

Once we update the theme on penny4nasa.org to this one for the initial release, you'll see the same copy.
