### ISSUE TITLE
Small link for "Found a bug? Idea for the website? Submit here!"

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#42]
Add a small link in the footer that says "Found a bug? Idea for the website? Submit here!" and link it to the non-github user issues page

**Comment by josephspens** [comment]
I think this should be on a secondary informational page, like volunteer or contact. The footer is too prominent, our product isn't the website, the product is Penny4NASA. We should focus the website to that goal.

**Comment by JohnLZeller** [comment]
What do you suggest for the secondary page? In either case it should be a small link available from every page. The footer is a nice place for that. I see this being sized similar to the plain text of a typical copyright mention on a website. Small, brief and tucked away.

The primary point is the site, but the point of the site is to put this all in the hands of the community. To that end, I would like a simple submit an issue link somewhere.

**Comment by josephspens** [comment]
Similar to #21
