### ISSUE TITLE
Budget Graph is cutoff on Android 4.1.2 using Firefox Beta 29

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#43]
Budget Graph is cutoff on Android 4.1.2 using Firefox Beta 29 with my Samsung Galaxy S2 Skyrocket.

![](http://s28.postimg.org/mgy7iz1jx/Screenshot_2014_04_20_11_50_51.png)

**Comment by josephspens** [comment]
We only support native mobile browsers.

**Comment by JohnLZeller** [comment]
I will check this on just a straight Firefox 29 on beta version but if it's still a problem we really need to look into fixing it because most of our mobile users are using Chrome and Firefox not native browsers

**Comment by josephspens** [comment]
Looks fine in mobile chrome (it's what I use), the only issue seems to be Firefox. But since analytics tells us none of our users use any mobile mozilla browser, it's not worth the effort.
