### ISSUE TITLE
Add link to Press Kit

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#44]
Add a link to Press Kit.

Being reviewed now and should be up soon

**Comment by josephspens** [comment]
There's already a link on the press page.

**Comment by JohnLZeller** [comment]
I mean the  actual link to the pdf. this is a reminder, I will do this

**Comment by josephspens** [comment]
This is a non-issue, once we put this theme on the current site it'll link to the correct PDF
