### ISSUE TITLE
Blog post text garbled on pages without <p> tag

### ISSUE THREAD

**Issue by JohnLZeller** [SpaceAdvocates/penny4nasa#54]
Blog post text is garbled on blog posts without the <p> tag, here is an example http://www.penny4nasa.org/2012/08/09/penny4nasa-response-to-the-white-house/

**Comment by josephspens** [comment]
This isn't a theme issue, if the content of the post is one giant text node, the theme will treat it as such.

If you want this post to behave as if it was properly wrapped in HTML, then the only thing you can do is go into Wordpress and clean it up.

**Comment by JohnLZeller** [comment]
Are you sure? I am skeptical only because this was not an issue with blog
posts in our previous theme, and the blog text was not formatted with HTML
tags 90% of the time. I assumed this was a styling issue that could be
solved with some additional styles hierarchy to differentiate between blog
post text and everything else.

**Comment by JohnLZeller** [comment]
PS Let's make sure to tag bugs like this as won't fix

**Comment by josephspens** [comment]
All of this

```
Director John Holdren
Office of Science and Technology Policy
The White House
Washington, DC 20502

Attention: Phil Larson

Dear Director Holdren,

Thank you for your response to our petition. We are encouraged to hear that the President shares our enthusiasm for space exploration and understands the pivotal role that NASA plays in achieving the dreams of all Americans. That being said, we are concerned that the message of our organization and the almost 30,000 individuals who have signed the petition is being overlooked.

First and foremost, we are not calling for a doubling of rockets launched or doubling the capabilities of Hubble becoming “100 times more powerful”. While real and certainly inspirational, the doubling of mission size and capability would be a byproduct of what we are advocating. By doubling NASA’s budget, from a mere 0.46% to a full 1%, or full penny on the taxpayer dollar, these activities become not just possibilities, but certainties.
```

Is one large text node, separated by new line characters, not by wrapped HTML elements.

![screen shot 2014-04-24 at 5 37 58 pm](https://cloud.githubusercontent.com/assets/933676/2795322/c3ee081e-cbf8-11e3-9e13-0de6237c62fe.png)
