### ISSUE TITLE
Add the video to the front page

### ISSUE THREAD

**Issue by josephspens** [SpaceAdvocates/penny4nasa#6]
Currently we're using a screenshot as a placeholder, we want to get the actual video in there before launch.

**Comment by JohnLZeller** [comment]
We'll get it uploaded to our channel and then embed. Go ahead and use another of our youtube videos as a placeholder and we can just change out the link

**Comment by JohnLZeller** [comment]
Video is being uploaded to the youtube page by Brad Goodspeed and will be left as unlisted until launch. Should be up within a few days

**Comment by JohnLZeller** [comment]
Video is up and unlisted
