### ISSUE TITLE
Verify the footer links are correct

### ISSUE THREAD

**Issue by josephspens** [SpaceAdvocates/penny4nasa#8]
Are these the correct links in the correct order? Are we missing any? Including ones we shouldn't? Some are duplicate from the header, so this might need some discussion.

**Comment by JohnLZeller** [comment]
I adjusted the footer to include the most important items. FAQ and Volunteer are tied for the same position, everything else is good.

**Comment by josephspens** [comment]
Alright, next time follow the contributing docs and open a PR. That way this issue automatically gets referenced and closed when you include the issue number in the PR message, and more importantly I can review your code changes. The only reason why I haven't been doing that is because I've been the only person working on this, but if other people start chipping in then I'll start opening PRs.

Does this mean you got the app working locally?
